[package]
name = "vectorsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-time = "1.0.0"
env_logger = "0.10.0"
hnsw_rs = "0.2.0"
itertools = "0.11.0"
parquet = "47.0.0"
rand = "0.8.5"
